### ISSUE TITLE
Gulp error "config not defined"

### ISSUE THREAD

**Issue by blackotruck** [jadjoubran/laravel5-angular-material-starter#397] opened 2016-09-06 13:41 UTC
- **I'm submitting a ...**
- [x] bug report
- [ ] feature request
- [ ] support request
- [ ] other (Please specify)
- **Provide information & explanation**
  On Tasks Elixir is required but then you are using config instead of Elixir.config, causing gulp to fail with a "config not defined" error
- **Got code samples?**
  `.pipe(gulpif(!config.production, sourcemaps.init()))`
  please add `var config = Elixir.config;` to prevent this.
- **Laravel & Angular version:** 3.2.0

**Comment by jadjoubran** [comment] 2016-09-08 19:56
Hi @blackotruck 
did you upgrade to Laravel 5.3 by yourself? Or did you update the `laravel-elixir` your package.json?
Because in 3.2 it should install version 5 so it shouldn't be an issue
This has been fixed in `version-3.4` though

**Comment by jadjoubran** [comment] 2016-09-14 18:12
Hi @blackotruck 
Any update on this issue?

**Comment by blackotruck** [comment] 2016-09-14 20:39
I was able to make it work with what i mentioned about the `config` variable. As forpackage.json, it's requiring `"laravel-elixir":"*"` and composer.json requires `"laravel/framework": "5.2.*"`.
Anyway, I haven't  got time to comeback to this, i'm switching to Ubuntu 16.04 (was previosuly using Windows 8).

**Comment by jadjoubran** [comment] 2016-09-14 21:27
The problem is that `laravel-elixir:"*"` which upgraded you to a newer version than allowed
You might have changed this inadvertently..
I'm going to close the issue (and the related one) based on this issue.. Let me know if it's not the case
Cheers 😄

**Closed as completed by jadjoubran** 2016-09-14 21:27 UTC
Labels: Support
