### ISSUE TITLE
vm.hide() in dialog service won't work

### ISSUE THREAD

**Issue by ghost** [jadjoubran/laravel5-angular-material-starter#336] opened 2016-06-16 10:21 UTC
- **I'm submitting a ...**
- [ ] bug report
- [ ] feature request
- [ ] support request
- [ ] other (Please specify)
- **Provide information & explanation**
- **Got code samples?**
  Make sure to use 3 backticks (and javascript or php after it to show your code) [More info](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#code)
  Also make sure to click on the _Preview_ button to double check your code formatting
- **Laravel & Angular version:** 3.2.0

**Comment by flick36** [comment] 2016-06-16 17:45
amm some info?

**Comment by jadjoubran** [comment] 2016-06-16 20:03
Yes please provide some info

**Comment by jadjoubran** [comment] 2016-06-21 14:32
I think this is a duplicate of https://github.com/jadjoubran/laravel5-angular-material-starter/issues/289
Feel free to re-open if you have another issue 😄

**Closed as completed by jadjoubran** 2016-06-21 14:32 UTC
Labels: Support
