### ISSUE TITLE
Error create components in js file

### ISSUE THREAD

**Issue by franklupo** [jadjoubran/laravel5-angular-material-starter#162] opened 2016-02-05 17:36 UTC
Hi,
`php artisan ng:component create_post_form`

in create_post_form.component.js error **app.components**

 `angular.module('app.components').directive('createPostForm', createPostFormComponent);`

replace in **app.controllers**

angular.module('app.controllers').directive('createPostForm', createPostFormComponent);
Thanks

**Comment by jadjoubran** [comment] 2016-02-05 20:33
Hi @franklupo 
Thanks for opening an issue

Unfortunately I can't understand what the issue is..
Can you please provide more information?

**Comment by franklupo** [comment] 2016-02-08 08:13
The generated js files has a 'app.components' error. 
I replece manual in 'app.controllers'

**Comment by jadjoubran** [comment] 2016-02-08 13:01
@franklupo so you didn't have an `app.components` in your `main.js` file?
I suspect this is the switch to the newer version of laravel-generators..
You can downgrade it in your composer.json if you'd like - just like in #161

**Comment by franklupo** [comment] 2016-02-08 17:18
No, in `main.js` the content is

> (function(){
>   "use strict";
> 
>   angular.module('app',
>       [
>       'app.controllers',
>       'app.filters',
>       'app.services',
>       'app.directives',
>       'app.routes',
>       'app.config',
>       'partialsModule'
>       ]);
> 
>   angular.module('app.routes', []);
>   angular.module('app.controllers', ['ui.router', 'ngMaterial', 'ngStorage', 'restangular', 'angular-loading-bar']);
>   angular.module('app.filters', []);
>   angular.module('app.services', []);
>   angular.module('app.directives', []);
>   angular.module('app.config', []);
> 
> })();

**Comment by jadjoubran** [comment] 2016-02-08 20:47
oh okay, thanks a lot for reporting it
This has been fixed as of 3.1 (unstable)

**Closed as completed by jadjoubran** 2016-02-08 20:47 UTC
Labels: Support
