### ISSUE TITLE
remove composer.lock file

### ISSUE THREAD

**Issue by winkbrace** [jadjoubran/laravel5-angular-material-starter#1] opened 2015-05-10 14:02 UTC
Hi, first of all thanks for creating this helpful boilerplate package! :)

It might be a good idea to remove the composer.lock file from the repo, so that `composer install -o` will always fetch the latest versions.

**Comment by jadjoubran** [comment] 2015-05-10 14:07
Thanks!

How can I remove `composer.lock` without adding it to `.gitignore`? Because adding it to `.gitignore` would be problematic for people using this repository

**Comment by winkbrace** [comment] 2015-05-10 14:13
Just remove it and commit :)
It doesn't have to be in this repository. That's all.

**Comment by jadjoubran** [comment] 2015-05-10 14:24
Okay but then next time I run composer install and commit it will be back no?

**Comment by winkbrace** [comment] 2015-05-10 14:27
Yes, but why would you composer install on this repository? That should only happen on a copy of it, right?

edit: or am I missing something?

**Comment by jadjoubran** [comment] 2015-05-10 14:33
Yeah here's the thing:
I'm planning on adding other libraries to this starter project. So next time I run `composer update` the composer.lock file will be generated again and it will be committed.
I also don't want to add it to .gitignore because anyone using this repository needs to have the composer.lock committed.

So I think the only solution would be to have a pre-commit hook that deletes my local composer.lock file.

What do you think?

**Comment by winkbrace** [comment] 2015-05-10 14:43
I see.

I can't think of a better solution than the pre-commit hook. It feels a little ugly though. I guess you have to decide if you think it is worth it.

**Comment by jadjoubran** [comment] 2015-05-10 14:53
it's definitely worth it!
I'll also update the contributing guide so that other contributors won't cause a regression for this.

**Comment by jadjoubran** [comment] 2015-05-10 17:15
Now that I think of it, it was fine to keep it because as soon as the end user runs `composer update` it'll automatically generate the new composer.lock. But I'm gonna keep the fix, that way when they run composer install (as mentioned in the guides), they'll get the newest dependencies.

Open a new issue if you have other suggestions!

And check this related package, I think you'll find it useful
https://github.com/jadjoubran/laravel5-generator

**Closed as completed by jadjoubran** 2015-05-10 17:15 UTC
Labels: enhancement
