### ISSUE TITLE
 possible problem with autoscroll

### ISSUE THREAD

**Issue by chojuanillo** [jadjoubran/laravel5-angular-material-starter#203] opened 2016-03-14 22:12 UTC
my problem is that I created two pages and move from one state to another page is overwritten at bottom for a moment. can you help me?.

I searched google and looks like it could be a problem autoscroll

**Comment by jadjoubran** [comment] 2016-03-15 08:28
@chojuanillo I didn't quite get what the issue
Can you show a screenshot?

**Comment by chojuanillo** [comment] 2016-03-15 18:56
thanks for your quick response. the problem is caused the transitions.less file. already resolved

**Comment by jadjoubran** [comment] 2016-03-15 19:17
Okay great!
So do you suspect there's an issue in `transitions.less`?

**Comment by chojuanillo** [comment] 2016-03-15 19:26
Yes I think so. my provoked me in every state change overprinting of the page at the bottom , for a few milliseconds , until it showed in its defined position, in this case at the top , but when his position was to the left, overprinting right , and so

**Comment by chojuanillo** [comment] 2016-03-15 19:28
in all browsers . I removed the css and disappeared

**Comment by jadjoubran** [comment] 2016-03-15 19:47
okay thanks, I'll take a look :smile:

**Comment by jadjoubran** [comment] 2016-03-22 22:15
I couldn't reproduce it, so closing for now

**Closed as completed by jadjoubran** 2016-03-22 22:15 UTC
Labels: bug, Support
