### ISSUE TITLE
Error when make Dialog, when call function DialogService.fromTemplate('register'); ~ v3.1

### ISSUE THREAD

**Issue by yosmelvin** [jadjoubran/laravel5-angular-material-starter#245] opened 2016-04-08 02:35 UTC
```
Error: [ng:areq] Argument 'RegisterController' is not a function, got undefined
http://errors.angularjs.org/1.5.0/ng/areq?p0=RegisterController&p1=not%20a%20function%2C%20got%20undefined
    at angular.js:68
    at assertArg (angular.js:1825)
    at assertArgFn (angular.js:1835)
    at angular.js:9831
    at setupControllers (angular.js:8852)
    at nodeLinkFn (angular.js:8898)
    at compositeLinkFn (angular.js:8226)
    at nodeLinkFn (angular.js:8973)
    at compositeLinkFn (angular.js:8226)
    at compositeLinkFn (angular.js:8229)(anonymous function) @ angular.js:13236(anonymous function) @ angular.js:9965processQueue @ angular.js:15560(anonymous function) @ angular.js:15568Scope.$eval @ angular.js:16820Scope.$digest @ angular.js:16636Scope.$apply @ angular.js:16928done @ angular.js:11266completeRequest @ angular.js:11464(anonymous function) @ angular.js:11374callback @ angular.js:11495
```

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
register.dialog.js
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

```
export class RegisterController{
    constructor(DialogService){
        'ngInject';

        this.DialogService = DialogService;
    }

    save(){
        //
    }

    hide(){
        this.DialogService.hide();
    }
}
```

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
register.html
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

```
<md-dialog-actions ng-controller="RegisterController as vm">
    <form ng-submit="vm.save()">
        <md-dialog-content>
            <h2 class="md-title">Register</h2>

            <md-input-container flex>
                <label>Data</label>
                <input type="text">
              </md-input-container>

        </md-dialog-content>

        <div class="md-actions" layout="row">
            <md-button type="button" ng-click="vm.hide()">Cancel</md-button>
            <md-button class="md-primary md-raised" type="submit">Save</md-button>
        </div>
    </form>
</md-dialog-actions>
```

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

How to make dialog on laravel angular material? because I got error like this when I try to call DialogService.fromTemplate('register');

**Comment by jadjoubran** [comment] 2016-04-08 12:39
Hi

Are you importing the controller?

**Comment by jadjoubran** [comment] 2016-04-08 12:39
Also which version if this starter are you using?

**Comment by yosmelvin** [comment] 2016-04-08 12:59
Version 3.1

**Comment by yosmelvin** [comment] 2016-04-08 15:23
How to importing the controller? Because i follow documentation

**Comment by jadjoubran** [comment] 2016-04-08 15:29
Hi @yosmelvin 
I have a solution for you but it requires using Controllers.. unfortunately as far as I know, there's no elegant way of solving this

1) you need to create a new `angular/index.controllers.js` file.. This is where you import the controller, just like you would do in the components, but of course replace the `angular.module('app.components').component` with `angular.module('app.controllers').controller`

2) **import** this file in your `angular/index.main.js` by writing: `import ./index.controllers`

3) add the `app.controllers` module to your `app` module (any line between 2 and 8)
and then define the `app.controllers` module underneath it by writing: `angular.module('app.controllers', []);`

Let me know if it works for you

**Comment by yosmelvin** [comment] 2016-04-11 04:31
It's work thank you, one more question how to passing data to dialogs? 

because when I try

```
options.locals = {
            items: response.data
          };
```

and passing `this.DialogService.fromTemplate('register', options);`

then to get with "Items" on class RegisterController its error, I see documentation on angular material to try inject "items"

**Comment by jadjoubran** [comment] 2016-04-11 14:22
Yes you need to inject `items` inside the controller.. As if it was a service for example. So just add it to the constrictor on top of ngInject

**Comment by yosmelvin** [comment] 2016-04-12 03:25
```
export class RegisterController{
    constructor(DialogService, $log, items){
        'ngInject';

        //this.scope = $scope;
        //this.items = items;
        this.log = $log;
        this.DialogService = DialogService;

        this.log.debug(this);

    }

    save(){
        //
    }

    hide(){
        this.DialogService.hide();
    }
}
```

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

angular.js:13236 Error: [$injector:unpr] Unknown provider: itemsProvider <- items <- RegisterInstagramController
http://errors.angularjs.org/1.5.0/$injector/unpr?p0=itemsProvider%20%3C-%20items%20%3C-%20RegisterInstagramController
    at angular.js:68
    at angular.js:4397
    at Object.getService [as get](angular.js:4550)
    at angular.js:4402
    at getService (angular.js:4550)
    at injectionArgs (angular.js:4574)
    at Object.invoke (angular.js:4596)
    at extend.instance (angular.js:9855)
    at nodeLinkFn (angular.js:8927)
    at compositeLinkFn (angular.js:8226)

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

when I inject Item error come out, how to solve this?

**Comment by jadjoubran** [comment] 2016-04-12 13:22
Hi @yosmelvin 
Please use 3 backticks "```" and then a breakline to format your code properly
[github flavored markdown](https://guides.github.com/features/mastering-markdown/)

**Comment by yosmelvin** [comment] 2016-04-12 14:38
Dear Joubran,

Done, i just add 3 backticks for format code properly

Warm regards,
Yos Melvin Tanoto

-------- Original Message --------

**Comment by jadjoubran** [comment] 2016-04-12 16:57
I think it's because you have the controller definition in the view.. 
Dialogs are very tricky.. the same issue was present in ionic 1's modals.. I think this was fixed in Angular 2 :/

Anyway, here's a way to fix it.. but it's not very elegant:
you can try defining the controller in the options.. 

```
var options = {
   locals: {items: response.data},
   controller: function(DialogService, $log, items){
       //your controller code here
    }
}
```

if this works, it means you need to `import` the controller at the top of the file and then replace the definition below with a reference:

```
var options = {
   locals: {items: response.data},
   controller: YourImportedControllerName
}
```

**Comment by yosmelvin** [comment] 2016-04-13 07:37
I tried your solution but its doesn't work properly , same error come out like when we are not import the controller

**Comment by jadjoubran** [comment] 2016-04-13 18:21
hmm maybe @jadsalhani has an idea? :/
I've successfully implemented the previous approach in one of my projects

**Comment by jadsalhani** [comment] 2016-04-13 19:24
The controller you created and imported in @jadjoubran 's last example, did you create is as a class or a function? because I think it should be a function, so something like 

```
export function RegisterController(items){
    'ngInject';
}
```

and then import that in the file that calls the `DialogService`

**Comment by flick36** [comment] 2016-04-15 22:01
I need a custom Dialog that receives data, but i can't make it work for the same reason of @yosmelvin i've tried that about make it a function and importing the file but i get the same error of  `Unknown provider`on the locale variable im triying to pass.

this works:

```
var options = {
   locals: {items: response.data},
   controller: function(DialogService, $log, items){
      'ngInject';
    }
}
```

but when triying to call the controller importing it it does not

So, my i ask why we have a `fromTemplate` method, but we don't have a `index.controller.js` in order to make them work? .-. and also why the directives were removed? i know that they were removed for the component one, but sometimes we need to create directves to manipulate the DOM and even the [angular docs](https://docs.angularjs.org/guide/component) tells you when not to use components as a directives replacement, so i suggest we bring them back, and well include the controllers in order to make the dialogs work. cause after all it's a starter, and just like you remove all the packages that most users won't require #92 well directives and controllers some users might or might not use them but i believe they're should be there. or maybe name the dialogs controllers something like `index.dialogs.js` and if we do that, maybe we should change the folder `angular/dialogs` to `angular/app/dialogs`

**Comment by flick36** [comment] 2016-04-16 06:30
I made it work, the problem is that when generating the template with the artisan command, it assigns the controller as: `<md-dialog ng-controller="NameController as vm">` and when doing 

```
var options = {
   locals: {items: response.data},
   controller: YourImportedControllerName
}
```

in the dialog template options we assing it again, so it causes a double injection of the controller,

so i fix it by removing the `ng-controller="NameController as vm"` in the template, and using:

```
var options = {
   locals: {items: response.data},
   controller: YourImportedControllerName,
   controllerAs: 'vm',
}
```

There's no need to change anything else the generator creates like for example converting the class to a function like @jadsalhani suggest.

I don't think it's a bug, because everything works if we leave it as default, i mean not deleting the `ng-controller` from the template, but if we need to pass data like in this case, it sure affects it somehow, i'm not an expert, and i'm not sure if this is the proper way to do it, but we can explain in the docs of this starter, that we should delete the ng-controller if we are going to pass data and assign the controller and the controllerAs in the options definition when calling the customDialog, unless there's another better way, wich i think there might be.

Also a must have docs, it's if @jadjoubran decide not to include the controllers as i suggest in my previous post, it's all this procces to make a custom Dialog using the DialogService, i mean all the imports and the file creations.

Also @yosmelvin  i recommend reading this [early styleguide on angular with ES6](https://github.com/rwwagner90/angular-styleguide-es6#controllers) i found, it helped me to solve this issue.

**Comment by jadjoubran** [comment] 2016-04-16 09:21
Hi @flick36 
Thanks for your comments
Indeed the `ng-controller="DialogController as vm"` shouldn't be there because it's causing an issue, I'll remove it and publish a new version
And thanks for pointing our the directives issue.. Indeed it should be fixed, but I need to find a way without creating a mess

**Closed as completed** 2016-04-16 09:30 UTC
Labels: Support
