### ISSUE TITLE
gulp && gulp watch gives Elixer version error on final.js 

### ISSUE THREAD

**Issue by kumarravisingh** [jadjoubran/laravel5-angular-material-starter#430] opened 2016-10-26 10:44 UTC
- **I'm submitting a ...**
- [x] bug report
- [x] support request
- **On my bash console i get this error**
  stream.js:74
    throw er; // Unhandled stream error in pipe.
    ^
  Error: ENOENT: no such file or directory, stat 'C:\laragon\www\cms\public\build\js\final-393dd5527e.js'
  at Error (native)

**On my browser console i get**

GET http://localhost:8000/build/js/final-7939682aa0.js fail to load response data
**And**
GET http://localhost:8000/build/js/final-7939682aa0.js  500 internal server error
- **Laravel & Angular version:** 3.4.0

**Comment by kumarravisingh** [comment] 2016-10-26 10:50
By searching I found out that it is .copy() function issue in gulpfile.js and I need to move them to storage/app/public
but here I don't think that will be an option.

**Stackoverflow answer**
[Stackoverflow solution](http://stackoverflow.com/a/39465922/3317153)
**Something like this :** 
removing these lines from gulpfile.js:

.copy('resources/assets/fonts', 'public/build/fonts')
.copy('resources/assets/images', 'public/build/images')

placing the fonts and images folders into the storage/app/public
running PHP artisan storage:link

changing the paths in the assets files to the new directory

running gulp

**Comment by jadjoubran** [comment] 2016-10-28 15:12
Thanks @kumarravisingh for this
To make sure I got what you mean: the problem only happens with any file type that isn't a JS, HTML or CSS right? So that's why the problem is for fonts and images
And the reason why they must be in build is to maintain the same paths? or can't they be fixed by just using absolute paths `/images/..` and `/fonts/..`?

**Comment by kumarravisingh** [comment] 2016-10-30 08:49
Oh. .sry for bad explanation  :(
All I know is there is an error whenever I run gulp && gulp watch which seems like a versioning issue.

stream.js:74
throw er; // Unhandled stream error in pipe.
^
Error: ENOENT: no such file or directory, stat 'C:\laragon\www\cms\public\build\js\final-393dd5527e.js'
at Error (native)

and I can't solve it.

**Comment by kumarravisingh** [comment] 2016-10-30 09:00
Also, there is no issue with version : 3.2, it is occurring in version 3.4 only.

**Comment by gultomic** [comment] 2016-10-30 12:25
laravel/elixir#626

**Comment by gultomic** [comment] 2016-10-30 12:33
I'm facing the same issue on windows, seems it because versioning
in my case have manually running `gulp` till the versioning filename get change then running `gulp watch`

hope this will help you too

**Comment by jadjoubran** [comment] 2016-11-08 21:14
Thanks @albertgultom for the temporary fix
Let's keep it open and hope for a fix in upstream

**Closed as completed** 2017-08-01 19:24 UTC
Labels: Upstream Fix

**Comment by craigjmidwinter** [comment] 2018-02-04 16:45
Sorry to bump an old issue, but the link to the fix for this is gone. Any idea what it was? Seeing the same versioning issue

**Comment by jadjoubran** [comment] 2018-02-05 12:54
Hi @wardcraigj 
so this [fix](https://stackoverflow.com/questions/39451859/laravel-elixir-6-getting-exception-on-gulp-watch/39465922#39465922) did not work for you?

**Comment by mtx-z** [comment] 2018-05-09 11:36
It didn't for me...

**Comment by jadjoubran** [comment] 2018-05-10 09:28
@mtx-z please open a new issue with the error message
Thanks!
